### ISSUE TITLE
Input not disabled when the intro video plays

### ISSUE THREAD

**Issue by SeleDreams** [saVantCZ/PS5reborn#16]
When the intro video is playing, the input isn't disabled which means we can select options without seeing what we're doing which is a problem.
It might be good to disable the menu input while the intro video plays

**Comment by saVantCZ** [comment]
I am sure input is disabled during intro video

only way to allow input is to pressing enter or controller A button while intro is playing, because "press the button" screen is actually preventing from any other input.

If you have disabled press the button screen via Theme Options, there is nothing i can do to prevent triggering some inputs during intro.
