### ISSUE TITLE
Games library becomes inaccessible again

### ISSUE THREAD

**Issue by novelandoweb** [saVantCZ/PS5reborn#35]
The game card library becomes inaccessible issue is occurring again even in version 2.3.1. The last version that works is 2.1.0 where it was fixed. Just remembering the problem occurs when you set the number of lines greater than 2 (I'm using 3).

**Comment by saVantCZ** [comment]
You should be using 2 rows, not 3 or anything else. Its required setting and theme is build on top of this.

You can set cover aspect ratio to 3:4 if you need more items in grid view, since this aspect ratio is supported and with 2 rows it shows more games then 1:1 ratio.

Thats why it is in readme file.

In future updates, i am planning to add block to make theme inaccessible with wrong settings, means if layout setting is not 2 rows and 50 spacing, theme will be blocked.

There will be no support for wrong settings
, sorry.

**Comment by novelandoweb** [comment]
I understand. It must be a lot of work. So I will have to stay on version 4.1.0. It's very good, by the way, I'm just sad that I didn't test the new features. Thanks.

**Comment by saVantCZ** [comment]
Maybe i will reconsider adding support for 3 rows... added to wip notes.
