### ISSUE TITLE
Miscounted Trophies

### ISSUE THREAD

**Issue by MoeinLM** [saVantCZ/PS5reborn#37]
I don't know if it's success story's bug or ps5 reborn's, but for example it says I have three bronze trophies and one silver for my RDR game and when I count them myself there are only four bronze trophies.

**Comment by saVantCZ** [comment]
It uses different logic, since successtory doesnt provide tools to make difference between gold silver or bronze, different logic is used to change rarity. 

Numeric part of trophies are correct, but list of trophies can be different. List trophies rarity colors are calculated by "earned" percentage, so 1-5 percent are gold, 5-10 are silver and rest is bronze... its purely cosmetic and there is no other way of doing this.

**Comment by saVantCZ** [comment]
But i can try something in next update to make it more precise

**Comment by saVantCZ** [comment]
Okay i made it 99 percent more precise by using different logic... wait for next update 2.4.1

**Comment by saVantCZ** [comment]
Update is released
